set(SOURCES
  constant_approximator.cpp
  fa_tree.cpp
  forest_approximator.cpp
  forest_trainer.cpp
  function_approximator.cpp
  function_approximator_factory.cpp
  gp.cpp
  gp_trainer.cpp
  gp_forest.cpp
  gp_forest_trainer.cpp
  orthogonal_split.cpp
  pwc_forest.cpp
  pwc_forest_trainer.cpp
  pwl_forest.cpp
  pwl_forest_trainer.cpp
  split.cpp
  split_factory.cpp
  trainer.cpp
  trainer_factory.cpp
)