set(SOURCES
  function_approximator.cpp
  gp.cpp
  gp_trainer.cpp
  gp_forest.cpp
  gp_forest_trainer.cpp
  pwc_forest.cpp
  pwc_forest_trainer.cpp
  pwl_forest.cpp
  pwl_forest_trainer.cpp
  trainer.cpp
  trainer_factory.cpp
)